export const APP_COMMAND_CHANNEL = 'app:command'
export const DOCUMENTS_OPEN_CHANNEL = 'documents:open'
export const DOCUMENTS_SAVE_AS_CHANNEL = 'documents:saveAs'
export const DOCUMENTS_SAVE_CHANNEL = 'documents:save'
export const EDITING_INSERT_TEXT_CHANNEL = 'editing:insertText'
export const EXPORTS_HTML_CHANNEL = 'exports:html'
export const EXPORTS_PDF_CHANNEL = 'exports:pdf'
export const SHELL_OPEN_EXTERNAL_CHANNEL = 'shell:openExternal'
